### ISSUE TITLE
 Comparator Errors in I20230920-1800

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#1380] opened 2023-09-21 06:24 UTC
There are many Comparator Errors in I20230920-1800 , Seems due to java21 merge.

https://download.eclipse.org/eclipse/downloads/drops4/I20230920-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

@jarthana @mpalat @subyssurendran666 @iloveeclipse please let us know.

**Comment by iloveeclipse** [comment] 2023-09-21 06:31
Duplicate of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1378

**Closed by iloveeclipse** 2023-09-21 06:31 UTC
