### ISSUE TITLE
Artifactcomparisons.zip contains unrelated (huge) doc bundles

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1703] opened 2024-01-08 12:33 UTC
Follow up on #1702.
- https://download.eclipse.org/eclipse/downloads/drops4/I20240108-0210/buildlogs.php
- https://download.eclipse.org/eclipse/downloads/drops4/I20240108-0210/buildlogs/comparatorlogs/artifactcomparisons.zip

The file [artifactcomparisons.zip](https://download.eclipse.org/eclipse/downloads/drops4/I20240108-0210/buildlogs/comparatorlogs/artifactcomparisons.zip) above is 100 MB size.

Most of the 100 MB is however inside files that are not compared during the baseline check at all!

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/964108/8d169202-61fb-4df1-81d9-70a740e03fd7)

**Comment by laeubi** [comment] 2024-01-08 12:35
> Most of the 100 MB is however inside files that are not compared during the baseline check at all!

Why do you think they are not compared?

**Comment by iloveeclipse** [comment] 2024-01-08 12:41
AFAIK they are only updated on last builds, and never show up in "unanticipated comparator" logs / never added to the "unstable" report.

**Comment by laeubi** [comment] 2024-01-08 12:44
> AFAIK they are only updated on last builds, and never show up in "unanticipated comparator" logs / never added to the "unstable" report.

Every change reported there means some javadoc is updated that will never show up unless you touch the bundle, at least Tycho can't know that this is something we ignore and therefore includes it in the  output where it is the collected.

So if that's fine, not only the report should ignore that but the part that collects  the differences must ignore this and not zip them up.

**Comment by iloveeclipse** [comment] 2024-01-08 12:59
> So if that's fine, not only the report should ignore that but the part that collects the differences must ignore this and not zip them up.

The file for `org.eclipse.jdt.doc.isv` is  https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml

Can you please give a hint which pom change would mute this kind of report for this bundle?

**Comment by iloveeclipse** [comment] 2024-01-08 13:12
Actually reportis OK, but the bundles should not show up in the classfile comparison (artifacts) zip, because there are no class files at all.

**Comment by laeubi** [comment] 2024-01-08 13:54
> Actually reportis OK, but the bundles should not show up in the classfile comparison (artifacts) zip, because there are no class files at all.

Baseline compare does not compare _classfiles_ it compares _jar files_ ... but something must create [artifactcomparisons.zip](https://download.eclipse.org/eclipse/downloads/drops4/I20240108-0210/buildlogs/comparatorlogs/artifactcomparisons.zip) seems to be [mb300_gatherEclipseParts.sh](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/cje-production/mbscripts/mb300_gatherEclipseParts.sh) that's the place where one should exclude unwanted path.

**Comment by sravanlakkimsetti** [comment] 2024-01-12 15:35
the comparator errors in doc bundles are not unanticipated. For this reason we never used to list them in `buildtimeComparatorUnanticipated.log.txt` but list them in `buildtimeComparatorDocBundle.log.txt` 

Towards the end of milestone we used to add a line in `forceQualifierUpdate.txt` to force new qualifier and generate new doc bundles.

My guess during the repo merge of eclipse.platform.commons the paths might have changes causing erroneous comparator errors

**Comment by laeubi** [comment] 2024-01-12 15:38
> the comparator errors in doc bundles are not unanticipated. 

They are please look at the resulting javadoc what has lost it references to the platform doc isv, mostly because last build did not produced any javadoc at all.

Also the ticket here is about the inclusion of the compared artifacts in the zip (what is correct).

**Comment by sravanlakkimsetti** [comment] 2024-01-12 15:52
We do compare all the jars that got generated/built even if there are no class files.

If you see `buildtimeComparatorDocBundle.log.txt` all the comparator errors from eclipse.platform.commons go into this
During the repo merge pde documentation is moved to eclipse.pde. So the comparator errors from pde documentation are not going to `buildtimeComparatorDocBundle.log.txt` any more. This is the root cause

Doc bundle errors(which we ignore. There should not be any error for the last build of milestone): https://download.eclipse.org/eclipse/downloads/drops4/I20240112-0850/buildlogs/comparatorlogs/buildtimeComparatorDocBundle.log.txt
Unanticipated errors(should not be there): https://download.eclipse.org/eclipse/downloads/drops4/I20240112-0850/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

The location of fix is in this method https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/blob/master/bundles/org.eclipse.releng.build.tools.comparator/src/org/eclipse/releng/build/tools/comparator/Extractor.java#L71-L80

The `docNamePattern` should match all the doc bundle names. 

Since the doc bundles moved around the pattern matcher in this method is failing.

**Comment by iloveeclipse** [comment] 2024-01-12 16:08
> The location of fix is in this method

@sravanlakkimsetti : could you provide a fix if you know which paths need to be updated?

**Comment by laeubi** [comment] 2024-01-12 16:08
> Doc bundle errors(which we ignore. There should not be any error for the last build of milestone): 

PDE does no longer ignores doc errors, they will fail the PR validation now.

**Comment by akurtakov** [comment] 2024-01-12 16:13
Please fix https://download.eclipse.org/eclipse/downloads/drops4/I20240112-0850/compilelogs/platform.doc.isv.javadoc.txt and run another I-build before trying anything else. It's ok to fail if javadoc failed to build and we are working to get javadoc failing earlier thus let's not go to extremes to have things the old way but rather fix issues.

**Comment by akurtakov** [comment] 2024-01-12 17:11
> Please fix https://download.eclipse.org/eclipse/downloads/drops4/I20240112-0850/compilelogs/platform.doc.isv.javadoc.txt and run another I-build before trying anything else. It's ok to fail if javadoc failed to build and we are working to get javadoc failing earlier thus let's not go to extremes to have things the old way but rather fix issues.

Done by @laeubi in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1716 and new I-build is running https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/87/

**Comment by sravanlakkimsetti** [comment] 2024-01-12 17:12
@akurtakov Errors in java doc generation needs to be fixed. There is no doubt here

The comparator errors are related to generated javadoc content. This means the javaDoc has been generated. Generated JavaDoc differs from build to build as there might be a new api added, new comments added in the code. So every time there is a change in javadoc comment or addition or deletion or deprecation of api will cause comparator errors to appear. This is because the code in another folder and javadoc generation happens in another folder. Or buildqualifier tool calculates based on the timestamp of javadoc generation folder. Because of this qualifier won't change though there is a change in the source code.

In the earlier days we used regenerate the javadoc bundles at fixed intervals using forcequalifierupdate in the javadoc generation folder and ignore the comparator errors arising from doc bundles. This was the we used to control the budles that gets listed in unanticipated errors

There are two solutions here:
1. ignore the comparator errors
2. force qualifier update for doc bundles everytime. I think org.eclipse.help.base build timestamp as qualifier. 

I think 2nd option is better here

**Comment by iloveeclipse** [comment] 2024-01-12 17:21
> force qualifier update for doc bundles everytime. I think org.eclipse.help.base build timestamp as qualifier.

Sounds OK, but why it wasn't considered before? Any drawbacks?

@sravanlakkimsetti : could you please create PR or give a hint what is needed to force the qualifier change on every build?

**Comment by laeubi** [comment] 2024-01-12 17:30
Qualifer aggregation is currently not done for bundles (but could) I plan to improve that but haven't  worked on it (yet).
I already improved Tycho comparator to "understand" what are real changes in javadoc as well so things have changed a bit already, but as said the "error" here is that platform.isv javadoc **was not generated at all** what went unoticed because we ignore the errors (but not for pde anymore).

So in worst case no one looks at it and you end up with empty javadoc or wrong javadoc or ...

**Comment by akurtakov** [comment] 2024-01-12 20:17
As visible by https://download.eclipse.org/eclipse/downloads/drops4/I20240112-1210/ - everything that was needed was to fix the javadoc building. I leave it to others to decide if some extra fancy scripts are gonna be added - for me have a clean build and totally fail otherwise is the only viable otherwise.

**Comment by laeubi** [comment] 2024-01-16 06:19
I'll close this for now, the inital issue is expected (all projects with comparator issues are generated).

If we want to:

- [ ] Exclude some comparator files from the generated zip
- [ ] Exclude some projects from the compartor logs

these are different issues and should be tracked separately and not as part of this ticket.

**Closed by laeubi** 2024-01-16 06:19 UTC
Labels: bug
