### ISSUE TITLE
org.eclipse.sdk.ide version showing as 4.31 in latest 4.32 I-builds

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.releng.aggregator#1879] opened 2024-03-06 18:23 UTC
Setting target to 4.32-I-builds with `org.eclipse.sdk.ide` unit resolves its version to `4.31.0.xxxx`

Load this target file and "Update IU versions from Repositories" or let it resolve itself.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="Test">
<locations>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/eclipse/updates/4.32-I-builds"/>
        <unit id="org.eclipse.sdk.ide" version="0.0.0"/>
    </location>
</locations>
</target>
```

As of today it resolves to `version="4.31.0.I20240306-0950"`

<img width="934" alt="Screenshot 2024-03-06 at 18 24 41" src="https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/600504/e53024a7-7d39-404c-bc48-fcbc9c9b50d7">

**Comment by iloveeclipse** [comment] 2024-03-06 18:35
Duplicate of https://github.com/eclipse-equinox/equinox/issues/552

**Closed by iloveeclipse** 2024-03-06 18:35 UTC
Labels: bug
