### ISSUE TITLE
Mysterious comparator errors on org.eclipse.jdt.core.compiler.batch

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1395] opened 2023-09-25 08:27 UTC
Follow up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1388

After "fixing" the original issue we've observed in https://download.eclipse.org/eclipse/downloads/drops4/I20230922-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt, the next build was OK but one build after was reported as unstable for exact same reason:

https://download.eclipse.org/eclipse/downloads/drops4/I20230923-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

```
1.  eclipse.jdt.core/org.eclipse.jdt.core.compiler.batch/pom.xml
   no-classifier: different
      org/eclipse/jdt/internal/compiler/ast/TypeReference.class: different
      org/eclipse/jdt/internal/compiler/parser/Parser.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]
```

However there is **no artifactcomparisons.zip** generated / linked to https://download.eclipse.org/eclipse/downloads/drops4/I20230923-1800/buildlogs.php that would show bytecode diff.

I assume this is a tycho issue, may be related to the ["special" way](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1211) we build org.eclipse.jdt.core.compiler.batch bundle for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1203.

Note: very last SDK build was OK, but only because we had **real** changes on batch compiler.

So what we need is:

1) Understand where is the problem of "changed" bytecode is coming from (recent tycho change?).
2) Make sure `artifactcomparisons.zip` is generated for `org.eclipse.jdt.core.compiler.batch` if `buildtimeComparatorUnanticipated.log.txt`
3) Understand where is the problem of "changed" bytecode is coming from (Java 21 branch merged recently to jdt?).

**Comment by iloveeclipse** [comment] 2023-09-25 08:27
@laeubi : could you please check this?

**Comment by laeubi** [comment] 2023-09-25 11:56
@iloveeclipse as far as I can see a released Tycho version is now used so you should not see any changes in Tycho

Only thing I could think of would be that a changed compiler is used in the I-Build but the published repository is published by another step using "old" compiler but the full I-Build is kind of a mystery, is this visible also in the local build when one runs https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/ ?

**Comment by iloveeclipse** [comment] 2023-09-25 12:00
> is this visible also in the local build

As far as I know the artifactcomparisons.zip & Co are only generated for eclipse.org I-builds / website publishing.

**Comment by laeubi** [comment] 2023-09-25 12:11
If you specify `-Dcompare-version-with-baselines.skip=false` it should be enabled and fail the build, I think the I build works with this disabled an scans the log for such messages later on but @mickaelistria can maybe better tell here.

**Comment by mickaelistria** [comment] 2023-09-25 13:17
To fail the build in case of errors `-Dcompare-version-with-baselines.skip=false` should do the trick.
But I-Builds use another strategy (IIRC they do run the apitools application after the build) as they generate some report flles that plain Tycho check doesn't generate.

**Comment by iloveeclipse** [comment] 2023-09-26 04:28
As expected, we have comparator errors in https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/

Same errors: https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

No zip file with diffs: https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/buildlogs.php

**Comment by laeubi** [comment] 2023-09-26 04:33
So how do I access the logfiles of the maven build?

I tried https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/ > "View the [logs for the current build](https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/testResults.php)." but this seems to only cover test result logs.

**Comment by iloveeclipse** [comment] 2023-09-26 04:36
https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/buildlogs.php
https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/buildlogs/mb060_run-maven-build_output.txt

**Comment by laeubi** [comment] 2023-09-26 04:40
@iloveeclipse thanks, looking at the logs the problem is quite clear because the message is emitted at the phase where the compiler is build for the I-Build itself, I think at that stage we should simply disable the baseline replace check all together.

**Comment by iloveeclipse** [comment] 2023-09-26 04:42
Why did it work before?

**Comment by laeubi** [comment] 2023-09-26 04:46
It seems now JDT produces a little bit different byte-code, so what happens is this:

1. compiler is compiled with "old" bytecode
2. this compiler is then used to produce a compiler jar with "new" bytecode
3. then this is deployed to the ibuild repository
4. on the next cycle the compiler is compiled with "old" bytecode and compared to the artifact with "new" bytecode 
5. --> comparator error

**Comment by iloveeclipse** [comment] 2023-09-26 04:50
OK, is the "old" compiler == 4.29 version? The "new" one is created after merging Java 21 branch to master, and we know we had generation changes, see https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1378 .

So @laeubi : could you push fixed maven call?

**Comment by laeubi** [comment] 2023-09-26 05:14
How to reproduce:

1. [fetch the aggregator repositories](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/#how-to-build-the-eclipse-sdk)
2. run `mvn clean install -pl :eclipse-sdk-prereqs,:org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99`
3. You see the follwoing warning in the build log:
```

[WARNING] MavenProject: org.eclipse.jdt:org.eclipse.jdt.core.compiler.batch:3.36.0-SNAPSHOT @ eclipse-aggregator/eclipse.platform.releng.aggregator/eclipse.jdt.core/org.eclipse.jdt.core.compiler.batch/pom.xml: baseline and build artifacts have same version but different contents
   no-classifier: different
      org/eclipse/jdt/internal/compiler/ast/ExpressionContext.class: different
      org/eclipse/jdt/internal/compiler/ast/TypeReference.class: different
      org/eclipse/jdt/internal/compiler/parser/Parser.class: different
```

**Comment by laeubi** [comment] 2023-09-26 05:40
@iloveeclipse this is a preliminary change required to fix the problem:
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1435

**Comment by akurtakov** [comment] 2023-09-26 05:43
one way to try workarounding the issue is:
* deploy latest batch compiler https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/
* switch to it in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse-platform-parent/pom.xml#L89 

Thinking more about it - it has to be done regardless of other fixes so all other builds use the new compiler not only the Ibuild.

**Comment by laeubi** [comment] 2023-09-26 05:45
Here is the fix for ibuild when JDT changes are merged:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1401

**Comment by iloveeclipse** [comment] 2023-09-26 06:26
@laeubi : thanks, I've merged both commits. Are we ready for new IBuild, or should we wait for regular one?

**Closed** 2023-09-26 06:25 UTC
Labels: bug, regression

**Comment by iloveeclipse** [comment] 2023-09-26 06:28
> Are we ready for new IBuild,

There are also two Javadoc errors shown in releng tests that we could fix first.

**Comment by iloveeclipse** [comment] 2023-09-26 07:02
> Thinking more about it - it has to be done regardless of other fixes so all other builds use the new compiler not only the Ibuild.

This should happen anyway after M1. Let us see if the two merged PRs fixed the issue.

**Comment by iloveeclipse** [comment] 2023-09-26 11:20
> Let us see if the two merged PRs fixed the issue.

Yep: https://download.eclipse.org/eclipse/downloads/drops4/I20230926-0600/
