### ISSUE TITLE
org.apache.commons.io got downgraded

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#489] opened 2022-08-18 05:14 UTC
<html>
<body>

org.apache.commons.io | 2.8.0.v20210415-0900 | 2.2.0
-- | -- | --

</body>
</html>

got downgraded in M3 candidate build this needs to be checked

cc @akurtakov @mickaelistria

**Comment by sravanlakkimsetti** [comment] 2022-08-18 05:40
This should be removed. We still have older version in our repository

**Comment by sravanlakkimsetti** [comment] 2022-08-18 05:45
screenshot of repo
![image](https://user-images.githubusercontent.com/77106773/185303256-01161759-ede1-40cc-b819-ead036f2981d.png)

**Comment by sravanlakkimsetti** [comment] 2022-08-22 12:19
Still a problem 
![image](https://user-images.githubusercontent.com/77106773/185919494-0fa2b586-b2ec-472a-a1fd-cb7a4e4e510e.png)

**Comment by akurtakov** [comment] 2022-08-22 13:00
@mickaelistria Can you take a look at this one?

**Comment by merks** [comment] 2022-08-22 14:05
The following PR's comment has details related specifically to this problem:

https://github.com/eclipse-equinox/p2/pull/136#issuecomment-1219404020

In particular there are no dependencies on the older version that are not satisfied by the newer version.  So why is it in the repo when it's not strictly required by anything?

I suspect strongly that this is a result of the repo is being assembled like this to include all dependencies (which was introduced during the 4.24 release cycle):
```
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-p2-repository-plugin</artifactId>
        <configuration>
        	<includeAllDependencies>true</includeAllDependencies>
        </configuration>
      </plugin>
```
I suspect that when Tycho is looking at package imports it resolves them to all bundles that provide a compatible version of the package, and then considers all those bundles to be dependencies, even if only one of them would be sufficient.

If that's the case, it seems the only way to eliminate this IU from the repo is to eliminate it from the target platform, but I don't think you can do that as long as you use put ` commons-fileupload`  in a `includeDependencyDepth="infinite` section.  I'd suggest moving it to a `includeDependencyDepth="none"` section.

**Comment by mickaelistria** [comment] 2022-08-22 15:57
> I'd suggest moving it to a includeDependencyDepth="none" section.

Although it would be more verbose, as we'd need to list transitive deps, it would actually allow to better control what we have in the .target and the final repo and would more easily allow to bump version of transitive deps as well.
So additionally to fixing this bug, it would also IMO better serve the goal of more efficiently managing dependencies, especially if many other Eclipse projects just pick the 3rd-party deps coming from Platform.

**Comment by mickaelistria** [comment] 2022-08-22 16:01
That said, I'm still too curious about the root cause and I'm still investigating what it can be.
I tried setting `includeAllDependencies` to `false` with a local build and could see that `commons-io:commons-io:jar:2.2:compile` is still listed when doing `mvn dependency:tree`.

**Comment by mickaelistria** [comment] 2022-08-22 16:21
Implemented the strategy suggested by @merks in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/493 . `mvn dependency:tree` doesn't show older commons-io any more.

**Closed** 2022-08-23 05:03 UTC
