### ISSUE TITLE
Aggregator-build and I-Build: I20240507-1800 fails with Internal compiler error

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.releng.aggregator#2014] opened 2024-05-07 21:06 UTC
The current `eclipse.platform.releng.aggregator` build consistently fails with an `Internal compiler error`.
Last successful build was the build input for last nights I-build.
From https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/master/2258/console
```
 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8-SNAPSHOT:compile (default-compile) on project org.eclipse.ui.ide: Compilation failure: Compilation failure: 
 [ERROR] /home/jenkins/agent/workspace/latform.releng.aggregator_master/eclipse.platform.ui/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/dialogs/ResourceFilterGroup.java: 
 [ERROR] 	/*******************************************************************************
 [ERROR] 	^
 [ERROR] Internal compiler error: java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding cannot be cast to class org.eclipse.jdt.internal.compiler.lookup.ArrayBinding (org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding and org.eclipse.jdt.internal.compiler.lookup.ArrayBinding are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @6c152246) at org.eclipse.jdt.internal.compiler.codegen.OperandStack.xaload(OperandStack.java:85)
 [ERROR] class org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding cannot be cast to class org.eclipse.jdt.internal.compiler.lookup.ArrayBinding (org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding and org.eclipse.jdt.internal.compiler.lookup.ArrayBinding are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @6c152246)
 [ERROR] -> [Help 1]
 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8-SNAPSHOT:compile (default-compile) on project org.eclipse.ui.ide: Compilation failure
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
     at java.lang.reflect.Method.invoke (Method.java:580)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
 Caused by: copied.org.apache.maven.plugin.CompilationFailureException: Compilation failure
     at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:433)
     at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.doCompile (AbstractOsgiCompilerMojo.java:407)
     at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute (AbstractOsgiCompilerMojo.java:388)
     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
     at java.lang.reflect.Method.invoke (Method.java:580)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
```

**Comment by HannesWell** [comment] 2024-05-07 21:19
To me it looks like this is caused by a recent JDT change:
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2354#discussion_r1593098564

**Comment by HannesWell** [comment] 2024-05-07 22:15
4.32 I-Build: I20240507-1800 failed with the same error. See https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/94/console.

**Comment by srikanth-sankaran** [comment] 2024-05-08 00:56
I have raised https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2423 which is reproducible against SDK 4.32 M1 (but goes back much longer back actually). It is this defect that is surfacing in the aggregator build failure now (even though that code does not use switch expressions: Operand stack contents were earlier tracked only when an exception handling switch expression was found; with https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2234 resolved, we track it at all times)

**Comment by srikanth-sankaran** [comment] 2024-05-08 01:39
PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2424 under test. Expect to merge shortly

**Comment by srikanth-sankaran** [comment] 2024-05-08 02:18
> PR [eclipse-jdt/eclipse.jdt.core#2424](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2424) under test. Expect to merge shortly

This is merged. Could a I-build be initiated asap ? @iloveeclipse @sravanlakkimsetti @HannesWell - FYI

**Comment by MohananRahul** [comment] 2024-05-08 02:25
> > PR [eclipse-jdt/eclipse.jdt.core#2424](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2424) under test. Expect to merge shortly
> 
> This is merged. Could a I-build be initiated asap ? @iloveeclipse @sravanlakkimsetti @HannesWell - FYI

https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/95/

**Comment by srikanth-sankaran** [comment] 2024-05-08 02:45
> > > PR [eclipse-jdt/eclipse.jdt.core#2424](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2424) under test. Expect to merge shortly
> 
> > 
> 
> > This is merged. Could a I-build be initiated asap ? @iloveeclipse @sravanlakkimsetti @HannesWell - FYI
> 
> 
> 
> https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/95/

Thanks Rahul!

**Comment by srikanth-sankaran** [comment] 2024-05-08 03:19
Build has progressed past Aggregator Maven build onto Gather Eclipse Parts. That ought to be a good sign.

**Comment by srikanth-sankaran** [comment] 2024-05-08 04:19
> > > PR [eclipse-jdt/eclipse.jdt.core#2424](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2424) under test. Expect to merge shortly
> > 
> > 
> > This is merged. Could a I-build be initiated asap ? @iloveeclipse @sravanlakkimsetti @HannesWell - FYI
> 
> https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/95/

@MohananRahul Where would this show up in the downloads page ? Is https://download.eclipse.org/eclipse/downloads/drops4/I20240507-2220/ the build ?

**Comment by iloveeclipse** [comment] 2024-05-08 04:21
Yes.
Comparator errors are unrelated to compiler.

**Comment by MohananRahul** [comment] 2024-05-08 04:23
> > > > PR [eclipse-jdt/eclipse.jdt.core#2424](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2424) under test. Expect to merge shortly
> > > 
> > > 
> > > This is merged. Could a I-build be initiated asap ? @iloveeclipse @sravanlakkimsetti @HannesWell - FYI
> > 
> > 
> > https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/95/
> 
> @MohananRahul Where would this show up in the downloads page ? Is https://download.eclipse.org/eclipse/downloads/drops4/I20240507-2220/ the build ?

Because Build is unstable due to comparator error.

**Comment by iloveeclipse** [comment] 2024-05-08 04:29
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1917 needed to fix comparator errors.
Once it succeeds (it waited for compiler fix), we could try to merge & build SDK once again.

**Comment by srikanth-sankaran** [comment] 2024-05-08 04:37
Thanks for the pointers/clarifications on the comparator errors. This looks ripe to be closed.

**Comment by iloveeclipse** [comment] 2024-05-08 05:01
Build started: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/96/

**Comment by iloveeclipse** [comment] 2024-05-08 06:39
Build hangs due some IT issues:
```
WARNING: Unable to create pod: kubernetes releng/aggrbuild-pod-wlgz8-568g4 because kubernetes resource quota exceeded. 
Failure executing: POST at: [https://10.30.0.1:443/api/v1/namespaces/releng/pods](https://10.30.0.1/api/v1/namespaces/releng/pods). Message: pods "aggrbuild-pod-wlgz8-568g4" is forbidden: exceeded quota: jenkins-instance-quota, requested: limits.memory=8Gi,requests.cpu=2, used: limits.memory=44Gi,requests.cpu=13950m, limited: limits.memory=49664Mi,requests.cpu=14950m. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=pods, name=aggrbuild-pod-wlgz8-568g4, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "aggrbuild-pod-wlgz8-568g4" is forbidden: exceeded quota: jenkins-instance-quota, requested: limits.memory=8Gi,requests.cpu=2, used: limits.memory=44Gi,requests.cpu=13950m, limited: limits.memory=49664Mi,requests.cpu=14950m, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
Retrying...
```

**Comment by iloveeclipse** [comment] 2024-05-08 06:50
I've created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4619

**Comment by HannesWell** [comment] 2024-05-08 07:11
> PR [eclipse-jdt/eclipse.jdt.core#2424](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2424) under test. Expect to merge shortly

Thank you for the prompt fix!

> Build hangs due some IT issues:
> 
> ```
> WARNING: Unable to create pod: kubernetes releng/aggrbuild-pod-wlgz8-568g4 because kubernetes resource quota exceeded. 
> Failure executing: POST at: [https://10.30.0.1:443/api/v1/namespaces/releng/pods](https://10.30.0.1/api/v1/namespaces/releng/pods). Message: pods "aggrbuild-pod-wlgz8-568g4" is forbidden: exceeded quota: jenkins-instance-quota, requested: limits.memory=8Gi,requests.cpu=2, used: limits.memory=44Gi,requests.cpu=13950m, limited: limits.memory=49664Mi,requests.cpu=14950m. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=pods, name=aggrbuild-pod-wlgz8-568g4, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "aggrbuild-pod-wlgz8-568g4" is forbidden: exceeded quota: jenkins-instance-quota, requested: limits.memory=8Gi,requests.cpu=2, used: limits.memory=44Gi,requests.cpu=13950m, limited: limits.memory=49664Mi,requests.cpu=14950m, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
> Retrying...
> ```

The build queue of the RelEng JIPP is quite long at the moment, so another job simply has to wait until that queue is (almost) empty.

**Comment by iloveeclipse** [comment] 2024-05-08 07:13
I also assuming this. Will retrigger the build after some time.

**Comment by iloveeclipse** [comment] 2024-05-08 08:12
After jenkins restart and jobs cleanup the next build started with no "Unable to create pod" issues: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/97/

**Comment by iloveeclipse** [comment] 2024-05-08 09:39
OK, https://download.eclipse.org/eclipse/downloads/drops4/I20240508-0410/ is there and is stable one. Closing.

**Closed by iloveeclipse** 2024-05-08 09:39 UTC
Labels: bug
