### ISSUE TITLE
Eclipse RCP feature can no longer be resolved with M2

### ISSUE THREAD

**Issue by cdietrich** [eclipse-platform/eclipse.platform.releng.aggregator#444] opened 2022-08-06 06:13 UTC
```
git clone https://github.com/itemis/xtext-reference-projects.git
cd xtext-reference-projects
scripts/domainmodel-2.28.sh
```

this fails since m2 with

```
*21:33:56*   [ERROR]   Software being installed: org.eclipse.rcp.feature.group 4.25.0.v20220728-1800
*21:33:56*   [ERROR]   Missing requirement: org.apache.xmlgraphics 2.6.0.v20210409-0748 requires 'java.package; org.apache.commons.io 1.3.1' but it could not be found
*21:33:56*   [ERROR]   Cannot satisfy dependency: org.apache.batik.css 1.14.0.v20210324-0332 depends on: java.package; org.apache.xmlgraphics.java2d.color 2.2.0
*21:33:56*   [ERROR]   Cannot satisfy dependency: org.eclipse.e4.rcp.feature.group 4.25.0.v20220727-1405 depends on: org.eclipse.equinox.p2.iu; org.apache.batik.css [1.14.0.v20210324-0332,1.14.0.v20210324-0332]
*21:33:56*   [ERROR]   Cannot satisfy dependency: org.eclipse.rcp.feature.group 4.25.0.v20220728-1800 depends on: org.eclipse.equinox.p2.iu; org.eclipse.e4.rcp.feature.group [4.25.0.v20220727-1405,4.25.0.v20220727-1405]
```

adding an explicit dependency to orbits commons.io helps

https://github.com/itemis/xtext-reference-projects/pull/285/files

<img width="610" alt="Bildschirmfoto 2022-08-06 um 08 03 07" src="https://user-images.githubusercontent.com/238736/183236800-4ffa3cc9-83f2-4611-95dc-df605a248981.png">

**Comment by merks** [comment] 2022-08-06 07:17
With the installer I can create a Platform installation from the M2 repo:

```
[2022-08-06 08:57:03] Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.ide [4.25.0,5.0.0) (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=win32)(osgi.ws=win32))))
[2022-08-06 08:57:03] Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group [4.25.0,5.0.0)
[2022-08-06 08:57:03] Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.feature.group [4.25.0,5.0.0)
[2022-08-06 08:57:03] Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.feature.group
[2022-08-06 08:57:03] Repository https://download.eclipse.org/releases/2022-09/202208051000
```

It produces this installation:

![image](https://user-images.githubusercontent.com/208716/183238261-a280ac16-0222-43f6-be8b-414596d3702d.png)

It contains this version of org.apache.commons.io:

![image](https://user-images.githubusercontent.com/208716/183238323-59593179-56f3-4e5e-9a3f-e510d8890fc5.png)

Looking at the generated report for the M2 repo the package requirement of org.apache.xmlgraphics version 1.3.1 or higher appears to be satisfied by org.apache.commons.io_2.8.0.v20210415-090's which provides the package with version 2.8.0:

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/releases/2022-09/https___download.eclipse.org_releases_2022-09_202208051000/org.apache.xmlgraphics_2.6.0.v20210409-0748.html#java.package;_org.apache.commons.io_1.3.1
https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/releases/2022-09/https___download.eclipse.org_releases_2022-09_202208051000/org.apache.commons.io_2.8.0.v20210415-0900.html#java.package;_version:OSGiVersion=2.8.0;_java.package:String=org.apache.commons.io

I see the same details in the Analyzer Editor:

![image](https://user-images.githubusercontent.com/208716/183238491-359a9b96-e0a4-4397-89aa-ec1bbd4c00d3.png)

![image](https://user-images.githubusercontent.com/208716/183238510-b5311d04-c7c2-4868-a5fe-e7d000721139.png)

**Comment by merks** [comment] 2022-08-06 08:07
I've hunted down your target file here:

https://github.com/itemis/xtext-reference-projects/blob/master/domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

If I look in the PDE editor to see how this target resolves. I see that org.apache.commons.io  is missing from the resolution:

![image](https://user-images.githubusercontent.com/208716/183239349-6703f798-1693-47c9-add5-1458ab9c8a6e.png)

But it's not missing from the repository:

![image](https://user-images.githubusercontent.com/208716/183239432-0cf2f8f8-4b36-465f-84de-7bf6f2fb1c0f.png)

Why is that?  You are using slicer mode:

![image](https://user-images.githubusercontent.com/208716/183239470-105e00b6-babd-4608-9db2-c8a1a14ab46c.png)

If I change them all to use planner mode then it's present:

![image](https://user-images.githubusercontent.com/208716/183239624-043c9800-e65a-4cb8-a111-895d2e494aaa.png)

Also resolution proceeds in that case (though note the warnings):
```
$scripts/domainmodel-2.28.sh
[INFO] Scanning for projects...
[INFO] Resolving target definition file:/D:/Users/xtext-test/xtext-reference-projects/domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target for environments=[macosx/cocoa/x86_64, win32/win32/x86_64, linux/gtk4], include source mode=honor, execution environment=StandardEEResolutionHints [executionEnvironment=OSGi profile 'JavaSE-11' { source level: 11, target level: 11}], remote p2 repository options=org.eclipse.tycho.p2.remote.RemoteAgent@3180a
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[WARNING] includeAllPlatforms='true' and includeMode='planner' are incompatible. ignore includeAllPlatforms flag
[WARNING] includeAllPlatforms='true' and includeMode='planner' are incompatible. ignore includeAllPlatforms flag
[INFO] Resolving dependencies of MavenProject: org.eclipse.xtext.example.domainmodel:org.eclipse.xtext.example.domainmodel:2.28.0-SNAPSHOT @ D:\Users\xtext-test\xtext-reference-projects\domainmodel\2.28.0\org.eclipse.xtext.example.domainmod.xml
[INFO] Fetching 202208051000&countryCode=us&timeZone=1&format=xml from https://www.eclipse.org/downloads/download.php?format=xml&file=/releases/2022-09/
```
This change of behavior is caused by this change:

https://github.com/eclipse-platform/eclipse.platform.ui/pull/200

I thought that was reverted but I see now that the comment was to just leave it out now.

https://github.com/eclipse-platform/eclipse.platform.ui/pull/203

I've **repeatedly** harped on the fact that removing bundle/plugin includes is not without impact.  This being the most recent recurrence on that front:

https://github.com/eclipse-platform/eclipse.platform.ua/pull/47

I.e., one issue is that it can cause sources to go missing when source features are generated.  But of course such a change also impacts the behavior of resolution, but then the argument is that the requirements of bundles will be satisfied anyway, so all such includes are pointless, useless, or worse than useless because they require effort to maintain.  But we've all overlooked the fact that PDE's slicer mode only follows strict includes (as I understand it), so such removals result in downstream clients needing to add back such removed things.

**Comment by mickaelistria** [comment] 2022-08-06 09:11
The referenced .target file has `includeMode="slicer"` which doesn't do transitive dependency resolution and is likely to fail whenever a transitive dependency is removed from feature definition. Using `includeMode="planner"` would lead to better results. If you're willing to keep using slicer, then it means that you take the responsibility of properly listing dependencies that are not immediately included but just required.

**Comment by cdietrich** [comment] 2022-08-06 09:33
But what has changed so why was it working before

**Comment by mickaelistria** [comment] 2022-08-06 10:12
> But what has changed so why was it working before. Even with slicer.

See last comment from @merks that explains that in details.

> why does the platform feature no longer include the plugin

First, nowadays and since p2, and even before, features are not meant to list all transitive deps but to group functional bits. Dependency resolution is something p2 does according to actual needs of the installed bundles. Repeating transitive deps in features is a duplication of concern, and as all duplication, is likely to become a source of failures or inconsistency when both diverge. As the feature is not what *hosts* the requirement to this dependency and this dependency is not part of a functional group, then it's more correct to remove it.
Then there is one issue, which is now representing the main issue when we want to update dependencies, that including bundles in features is what is now causing the most annoyance/trouble/work/delay when updating a dependency (latest occurrence of this weekly-ish problem would be #442 ). This is caused by feature inclusion which enforce one particular version when we actually don't need the feature to do it, as described in former paragraph.
So overally, the plugin is not included because it's likely to be the cause of extra work and extra bugs that we can easily avoid with proper usage of p2 (planner).

**Comment by akurtakov** [comment] 2022-08-08 11:46
Closing as there is nothing to be done on platform side.

**Closed by akurtakov** 2022-08-08 11:46 UTC
