### ISSUE TITLE
Eclipse 4.24 Prerequisites: Orbit

### ISSUE THREAD

**Issue by SDawley** [eclipse-platform/eclipse.platform.releng.aggregator#172] opened 2022-03-30 17:32 UTC
Platform's M1 is on April 8th. Last build for M1 is 18:00 ET on April 6th.
@jonahgraham Is there a new version for M1?

**Comment by jonahgraham** [comment] 2022-03-31 00:56
@SDawley - there will be a new version - due to [Bug 568936](https://bugs.eclipse.org/bugs/show_bug.cgi?id=568936) I am trying to get it done earlier than normal, but I am struggling to find the necessary time.

**Comment by jonahgraham** [comment] 2022-04-03 23:59
@SDawley the new URL for 2022-06 M1 is https://download.eclipse.org/tools/orbit/downloads/drops/S20220403232146/ to update this line (and comment):

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/7aa6ff4ba08601f8e5152a95d29b248e490f5fe8/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L137-L140

**Comment by sravanlakkimsetti** [comment] 2022-04-26 10:03
@jonahgraham Do we have a new version for 4.24 M2?

**Comment by jonahgraham** [comment] 2022-04-26 18:49
Here you go: https://download.eclipse.org/tools/orbit/downloads/drops/S20220426182153/

**Comment by HannesWell** [comment] 2022-04-26 21:45
While assuming my recently added OSGi dependencies are not vetted correctly I requested a review for them.
In the end only reviews for jackson were created. I just want to inform you about that, since the associated change seems to add new jackson-deps (at least it seems to be the reason why it is failing on first sight) and in case you wonder.
```
[INFO] Setting up a review for p2/orbit/p2.eclipse.plugin/com.fasterxml.jackson.core.jackson-core/2.12.1.v20210128-1726.
[INFO]  - Created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2423
[INFO] Setting up a review for p2/orbit/p2.eclipse.plugin/com.fasterxml.jackson.core.jackson-databind/2.12.1.v20210128-1726.
[INFO]  - Created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2424
[INFO] Setting up a review for p2/orbit/p2.eclipse.plugin/com.fasterxml.jackson.core.jackson-annotations/2.12.1.v20210128-1726.
[INFO]  - Created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2425
```

**Comment by jonahgraham** [comment] 2022-04-27 02:42
There are two different things going on.

1. The build failed because the target platform specified a version of jackson that doesn't exist in 2022-06 M2 (it was updated). This should be fixed by #238 
2. The license issue is caused by https://github.com/eclipse/dash-licenses/issues/81 - see [comment I added to GitLab](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2423#note_710385):
> [@wbeaton](https://github.com/wbeaton) - FWIW the Eclipse Platform created this (And [#2424 (closed)](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2424) [#2425 (closed)](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2425)) because of https://github.com/eclipse/dash-licenses/issues/81 combined with Orbit just having updated the version it ships of these libraries today.

**Comment by sravanlakkimsetti** [comment] 2022-05-16 08:53
Any update for 4.24 M3

**Comment by jonahgraham** [comment] 2022-05-17 14:58
@sravanlakkimsetti there will be an update later today. I am hoping that [jboss](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1312) issue can be resolved so I don't have to work around the problem to produce an M3.

**Comment by jonahgraham** [comment] 2022-05-17 19:09
4.24 M3 Orbit: https://download.eclipse.org/tools/orbit/downloads/drops/S20220517184036/

**Comment by sravanlakkimsetti** [comment] 2022-05-24 05:29
We are in RC phase now. Please let us know once the the final release version is available.
Last build for RC2 is at June 1 at 6PM eastern. It would be helpful if we get the release version by May 31.

**Comment by sravanlakkimsetti** [comment] 2022-05-31 03:15
Platform RC2 final build is on June 1(tomoirrow). Do we have the release build for Simrel?

**Comment by jonahgraham** [comment] 2022-05-31 18:25
There is no new content for RC2 - only the URL will change. I will provide the new URL when it is ready.

**Comment by jonahgraham** [comment] 2022-06-01 01:34
Here is the new URL https://download.eclipse.org/tools/orbit/downloads/drops/R20220531185310/repository/

**Comment by sravanlakkimsetti** [comment] 2022-06-01 03:46
Closing this now

**Closed by sravanlakkimsetti** 2022-06-01 03:46 UTC
