### ISSUE TITLE
Comparator Errors in I20240123-1800

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#1744] opened 2024-01-24 05:08 UTC
See 
https://download.eclipse.org/eclipse/downloads/drops4/I20240123-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

1.  rt.equinox.p2/bundles/org.eclipse.equinox.p2.director/.polyglot.META-INF
   no-classifier: different
      org/eclipse/equinox/internal/p2/director/SimplePlanner.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

2.  eclipse.pde/ds/org.eclipse.pde.ds.annotations/.polyglot.META-INF
   no-classifier: different
      org/eclipse/pde/ds/internal/annotations/ComponentActivationAnnotation.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

3.  eclipse.platform/debug/org.eclipse.debug.examples.core/.polyglot.META-INF
   no-classifier: different
      org/eclipse/debug/examples/pdavm/PDAVirtualMachine.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

4.  eclipse.platform.ui/tests/org.eclipse.jface.tests/.polyglot.META-INF
   no-classifier: different
      org/eclipse/jface/tests/viewers/BaseLimitBasedViewerTest$TestComparator.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

**Comment by iloveeclipse** [comment] 2024-01-24 05:57
Haven't checked diffs yet, but potential candidate would be https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1898.

Links
- https://download.eclipse.org/eclipse/downloads/drops4/I20240123-1800/buildlogs/comparatorlogs/artifactcomparisons.zip
- https://download.eclipse.org/eclipse/downloads/drops4/I20240123-1800/buildlogs.php

**Comment by iloveeclipse** [comment] 2024-01-24 08:14
Looking at it now, ComponentActivationAnnotation diff points to https://github.com/eclipse-jdt/eclipse.jdt.core/commit/76d44c87044b896a39d2d69a34c79862becddf5f / https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1885.

The code in `org.eclipse.pde.ds.internal.annotations.ComponentActivationAnnotation.isType()` is actually not clean and should be fixed - it defines a local variable that is not used. This variable's number is now different.

Small example showing the same effect:
```
public record X(Number number) {
	
	boolean isInteger() {
		return number instanceof Integer number; // <-- first "number" is field, second is local variable
	}
}
```

and the diff between different compiler commits looks like
![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/964108/793349e2-4a3c-4841-94ef-2fff66fef2ea)

**Comment by iloveeclipse** [comment] 2024-01-24 09:36
The change in SimplePlanner is also coming from https://github.com/eclipse-jdt/eclipse.jdt.core/commit/76d44c87044b896a39d2d69a34c79862becddf5f.

**Comment by srikanth-sankaran** [comment] 2024-01-24 10:03
> The change in SimplePlanner is also coming from [eclipse-jdt/eclipse.jdt.core@76d44c8](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/76d44c87044b896a39d2d69a34c79862becddf5f).

Yes, here again, the slots of a secret variable and user defined variables got assigned differently. I don't see a real issue here

**Comment by srikanth-sankaran** [comment] 2024-01-24 10:04
> Looking at it now, ComponentActivationAnnotation diff points to [eclipse-jdt/eclipse.jdt.core@76d44c8](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/76d44c87044b896a39d2d69a34c79862becddf5f) / [eclipse-jdt/eclipse.jdt.core#1885](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1885).

I don't see a real problem here. Cleaning up the code to remove the unused variable looks good. +1

**Comment by iloveeclipse** [comment] 2024-01-24 10:07
`org.eclipse.debug.examples.pdavm.PDAVirtualMachine.iAdd(PDAThread)` is also coming from eclipse-jdt/eclipse.jdt.core@76d44c8, same "hidden" variable number change.

**Comment by srikanth-sankaran** [comment] 2024-01-24 10:11
> `org.eclipse.debug.examples.pdavm.PDAVirtualMachine.iAdd(PDAThread)` is also coming from [eclipse-jdt/eclipse.jdt.core@76d44c8](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/76d44c8), same "hidden" variable number change.

Confirmed

**Comment by srikanth-sankaran** [comment] 2024-01-24 10:11
So is org/eclipse/jface/tests/viewers/BaseLimitBasedViewerTest$TestComparator.class

**Comment by iloveeclipse** [comment] 2024-01-24 10:12
And `org.eclipse.jface.tests.viewers.BaseLimitBasedViewerTest.TestComparator.compare(Viewer, Object, Object)`is same story.

So @srikanth-sankaran : should I bump bundles below or do you want to change something in jdt?
- rt.equinox.p2/bundles/org.eclipse.equinox.p2.director (for SimplePlanner)
- eclipse.platform/debug/org.eclipse.debug.examples.core (for PDAVirtualMachine)
- eclipse.platform.ui/tests/org.eclipse.jface.tests (for TestComparator)

**Comment by srikanth-sankaran** [comment] 2024-01-24 10:16
I asked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1686#issuecomment-1867368067 : 

```
Is this list supposed to be exhaustive ? How come it doesn't include jdt.core ?? I see one comparator diff in WrapPreparator which is what I am looking at presently to see if the changes are justified.
```

In the present case too I see a comparator difference `eclipse.jdt.core/org.eclipse.jdt.core/target/artifactcomparison/no-classifier/org/eclipse/jdt/internal/codeassist/CompletionEngine.class` 

Why is that not captured in this ticket ?? Is there some defect in the automation that summarizes the comparator differences ?

**Comment by srikanth-sankaran** [comment] 2024-01-24 10:18
> And `org.eclipse.jface.tests.viewers.BaseLimitBasedViewerTest.TestComparator.compare(Viewer, Object, Object)`is same story.
> 
> So @srikanth-sankaran : should I bump bundles below or do you want to change something in jdt?
> 
> * rt.equinox.p2/bundles/org.eclipse.equinox.p2.director (for SimplePlanner)
> * eclipse.platform/debug/org.eclipse.debug.examples.core (for PDAVirtualMachine)
> * eclipse.platform.ui/tests/org.eclipse.jface.tests (for TestComparator)

Yes, please proceed - I did try to minimize these noise diffs tweaking things when a JDT/Core test failed due to such innocuous changed. But there are scenarios not captured there it would seem.

But we will have to deal with this a few more times. I anticipate that code generation rework for patterns would eliminate at least some of these hidden slots.

**Comment by iloveeclipse** [comment] 2024-01-24 10:41
OK, created
* https://github.com/eclipse-equinox/p2/pull/437
* https://github.com/eclipse-platform/eclipse.platform/pull/1142
* https://github.com/eclipse-platform/eclipse.platform.ui/pull/1550

Once they are merged, will trigger new build.

**Comment by iloveeclipse** [comment] 2024-01-24 11:56
Triggered https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/108/

**Comment by iloveeclipse** [comment] 2024-01-24 13:25
Build https://download.eclipse.org/eclipse/downloads/drops4/I20240124-0650/ is stable.

**Closed by iloveeclipse** 2024-01-24 13:25 UTC
Labels: bug
